# Generated by Django 5.2.8 on 2025-11-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='votes',
        ),
        migrations.AddField(
            model_name='leader',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='leaders/'),
        ),
    ]
