# Generated by Django 5.2.8 on 2025-11-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_remove_leader_votes_leader_bio_leader_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='photo',
        ),
        migrations.AddField(
            model_name='leader',
            name='biography',
            field=models.TextField(default='No biography provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leader',
            name='community_contribution',
            field=models.TextField(default='No contribution provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leader',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
