# Generated by Django 5.2.8 on 2025-11-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_remove_leader_bio_remove_leader_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
