# Generated by Django 5.2.8 on 2025-11-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_leader_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leader',
            name='votes',
        ),
        migrations.AlterField(
            model_name='leader',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='leader',
            name='party',
            field=models.CharField(max_length=255),
        ),
    ]
