# Generated by Django 5.2.8 on 2025-11-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_remove_leader_votes_alter_leader_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='leaders/'),
        ),
    ]
