# Generated by Django 5.2.8 on 2025-11-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_leader_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leader',
            old_name='image',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='leader',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='community_contribution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leader',
            name='party',
            field=models.CharField(max_length=100),
        ),
    ]
