# Generated by Django 5.2.8 on 2025-11-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0007_rename_image_leader_photo_alter_leader_biography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
