# Generated by Django 5.2.8 on 2025-11-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0008_leader_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('keyword', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='resources/')),
            ],
        ),
    ]
