# Generated by Django 5.2.8 on 2025-11-29 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_resource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
